2023-06-20 09:11:33,260	INFO trainable.py:173 -- Trainable.setup took 20.753 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
2023-06-20 09:11:33,264	WARNING util.py:68 -- Install gputil for GPU system monitoring.
i 0
2023-06-20 09:13:33,346	ERROR actor.py:1175 -- Worker exits with an exit code None.
 Traceback (most recent call last):
  File "python\ray\_raylet.pyx", line 1695, in ray._raylet.execute_task_with_cancellation_handler
  File "python\ray\_raylet.pyx", line 1380, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1431, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1434, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1438, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1378, in ray._raylet.execute_task.function_executor
  File "C:\Users\Roumaissa\Desktop\Thesis\againtry\venv\lib\site-packages\ray\_private\function_manager.py", line 724, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\Roumaissa\Desktop\Thesis\againtry\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\Roumaissa\Desktop\Thesis\againtry\venv\lib\site-packages\ray\rllib\utils\actor_manager.py", line 176, in apply
    return func(self, *args, **kwargs)
  File "C:\Users\Roumaissa\Desktop\Thesis\againtry\venv\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 86, in <lambda>
    lambda w: w.sample(), local_worker=False, healthy_only=True
  File "C:\Users\Roumaissa\Desktop\Thesis\againtry\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\Roumaissa\Desktop\Thesis\againtry\venv\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 915, in sample
    batches = [self.input_reader.next()]
  File "C:\Users\Roumaissa\Desktop\Thesis\againtry\venv\lib\site-packages\ray\rllib\evaluation\sampler.py", line 92, in next
    batches = [self.get_data()]
  File "C:\Users\Roumaissa\Desktop\Thesis\againtry\venv\lib\site-packages\ray\rllib\evaluation\sampler.py", line 277, in get_data
    item = next(self._env_runner)
  File "C:\Users\Roumaissa\Desktop\Thesis\againtry\venv\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 323, in run
    outputs = self.step()
  File "C:\Users\Roumaissa\Desktop\Thesis\againtry\venv\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 379, in step
    self._base_env.send_actions(actions_to_send)
  File "C:\Users\Roumaissa\Desktop\Thesis\againtry\venv\lib\site-packages\ray\rllib\env\vector_env.py", line 464, in send_actions
    ) = self.vector_env.vector_step(action_vector)
  File "C:\Users\Roumaissa\Desktop\Thesis\againtry\venv\lib\site-packages\ray\rllib\env\vector_env.py", line 353, in vector_step
    results = self.envs[i].step(actions[i])
  File "C:\Users\Roumaissa\Desktop\Thesis\againtry\envext3_R.py", line 157, in step
    done = False
  File "C:\Users\Roumaissa\Desktop\Thesis\againtry\envext3_R.py", line 157, in step
    done = False
  File "_pydevd_bundle\pydevd_cython_win32_39_64.pyx", line 1179, in _pydevd_bundle.pydevd_cython_win32_39_64.SafeCallWrapper.__call__
  File "_pydevd_bundle\pydevd_cython_win32_39_64.pyx", line 620, in _pydevd_bundle.pydevd_cython_win32_39_64.PyDBFrame.trace_dispatch
  File "_pydevd_bundle\pydevd_cython_win32_39_64.pyx", line 1095, in _pydevd_bundle.pydevd_cython_win32_39_64.PyDBFrame.trace_dispatch
  File "_pydevd_bundle\pydevd_cython_win32_39_64.pyx", line 1057, in _pydevd_bundle.pydevd_cython_win32_39_64.PyDBFrame.trace_dispatch
  File "_pydevd_bundle\pydevd_cython_win32_39_64.pyx", line 317, in _pydevd_bundle.pydevd_cython_win32_39_64.PyDBFrame.do_wait_suspend
  File "C:\Users\Roumaissa\AppData\Local\JetBrains\PyCharm Community Edition 2022.2.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1160, in do_wait_suspend
    self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread)
  File "C:\Users\Roumaissa\AppData\Local\JetBrains\PyCharm Community Edition 2022.2.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1175, in _do_wait_suspend
    time.sleep(0.01)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "python\ray\_raylet.pyx", line 1796, in ray._raylet.task_execution_handler
  File "python\ray\_raylet.pyx", line 1725, in ray._raylet.execute_task_with_cancellation_handler
AttributeError: 'ray._raylet.CoreWorker' object has no attribute 'actors'